### ISSUE TITLE
# Question of  training shuffle

### ISSUE THREAD

**Issue by accuracy-maker** [thuml/Autoformer#118]
Thank you for sharing your great work. I notice the parameter of training shuffle is True. I think it will break the order of time series. I don't understand

**Comment by ChuckTG** [comment]
Shuffling is for the batches and not for the actual timesteps. For example you have two batches of your time series and let's say the input of the model has to be of size [n_batches, timesteps](No feature dimension for simplicity). What shuffling will do is shuffle the order that the model receives the batches and not the actual timesteps. Lets say we have two batches with 5 timesteps [[1,2,3,4,5],[0,-1,-2,-3,-4]] (n_batches=2,timesteps=5). We can shuffle the order of the batches and have [[0,-1,-2,-3,-4],[1,2,3,4,5]], but we are not shuffling the actual timesteps [[2,5,3,1,4],[-3,0,-2,-1,-4]] because that would hurt the model.

**Comment by accuracy-maker** [comment]
Thank you for answer this, I understand it!

**Comment by wuhaixu2016** [comment]
Thanks for your valuable explanation! @ChuckTG

**Comment by Zero-coder** [comment]
well done~
