### ISSUE TITLE
Confusing about how to plot true vs predicted curves based on this dimensions (65, 2, 1)

### ISSUE THREAD

**Issue by Med-Rokaimi** [thuml/Autoformer#157]
Hey, thank you so much for this so amazing work.
I'm running the Autofrom model with my own database (4 features including the target as inputs, and the one output target). So, the setting seems like this:
`
args.bucket_size = 4
args.features = 'MS'
args.seq_len = 14
args.label_len = 7
args.pred_len = 2
args.enc_in = 4
args.dec_in =4
args.c_out = 1
`
So, the output in the preds.npy and true.npy are like this:

data_pred shape (64, 2, 1), data_true shape (64, 2, 1)

data_pred 
[[[52.127125]
  [51.52287 ]]

 [[50.261303]
  [51.50038 ]]

[[52.20441 ]
  [53.115993]]]

 data_true 
[[[51.8 ]
  [51.09]]

 [[51.09]
  [53.6 ]]

 [[53.6 ]
  [54.3 ]]]
As you can see, the second column from each raw in the data_true = the first column from the next raw as the pred_len = 2.
I'm confusing how should I plot the curve which compare the truth and prediction values and how the MSE is being calculated as each prediction is two steps. does it should suitable to take only the first column ? 
That what I have done:
plt.plot(data_gt[:,0])# Since the prediction.shape is [1, 24, 7], the batch has only 1 and the index can only be 0 or -1, both of which represent the dimension of the batch itself. It is different if the np file is loaded
`
plt.plot(data_true[:,0])
plt.plot(data_pred[:,0])
plt.show()
`
But I don't think this will be systematic or will represent the actual performance for two steps prediction.
Can you help please?

**Comment by wuhaixu2016** [comment]
Hi, thanks for your insterests in our paper and repo.

Due to the limitation of matplotlib, you can only plot the curve of one variate from one forecasting step once a time.

For “data_pred shape (64, 2, 1), data_true shape (64, 2, 1)”, 64 is the batch size, 2 is for temporal dimension and 1 is for the variate.

Thus, if you want to visualize the data_pred and data_true, you can just adopt `plt.plot(data_true[i,:,0]) plt.plot(data_pred[i,:,0]) plt.show()`, where i is in the range of [0,64).

**Comment by Med-Rokaimi** [comment]
Thank you so much this makes sense.
