### ISSUE TITLE
What does 'OT' mean?

### ISSUE THREAD

**Issue by YYtang6** [thuml/Autoformer#2]
I saw the OT column name in every dataset, but I don't know what is it.
![B24E02B6-15EB-42e1-8B87-74E3577A391C](https://user-images.githubusercontent.com/22828721/141943290-c462119a-326b-4f7b-8f21-150f76366ef2.png)

Could you please explain it?

**Comment by wuhaixu2016** [comment]
See line27 in run.py for the argument 'target' (the default value is 'OT').
It indicates the target dimension in the univariate forecasting setting.

**Comment by YYtang6** [comment]
> See line27 in run.py for the argument 'target' (the default value is 'OT'). It indicates the target dimension in the univariate forecasting setting.

So, it means nothing in S or MS task? But where dose it come from in the dataset? Thanks.

**Comment by wuhaixu2016** [comment]
It means nothing in the **multi-variate forecasting setting**. Because we need to predict the data in all the dimensions, it is meaningless to decide which one is the target. This one is only used in the S and MS tasks.

This repo provides the after-processed data. We standard the data schema, including the column name and the time stamp. 

If you want to process the raw data, you can ref to the links in our paper (page 7).

<img width="832" alt="截屏2021-11-16 下午4 56 34" src="https://user-images.githubusercontent.com/24385030/141954074-a2e4275e-6d02-4677-b211-40d38b855967.png">

**Comment by YYtang6** [comment]
thanks very much.
